-- 1. 单列主键（最常见的主键类型）
CREATE TABLE pk_single_column (
    id              NUMBER PRIMARY KEY,
    name            VARCHAR2(100),
    email           VARCHAR2(100),
    create_time     DATE DEFAULT SYSDATE
);

-- 2. 复合主键（多个列组合作为主键）
CREATE TABLE pk_composite (
    department_id   NUMBER,
    employee_id     NUMBER,
    name            VARCHAR2(100),
    PRIMARY KEY (department_id, employee_id)
);

-- 3. 使用序列生成主键
CREATE SEQUENCE seq_pk_sequence
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE pk_sequence (
    id              NUMBER PRIMARY KEY,
    product_name    VARCHAR2(200),
    price           NUMBER(10,2),
    stock           NUMBER
);

-- 4. IDENTITY列主键（Oracle 12c+支持）
CREATE TABLE pk_identity (
    id              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50),
    password_hash   VARCHAR2(256),
    enabled         NUMBER(1) DEFAULT 1
);
-- 5. IDENTITY BY DEFAULT
CREATE TABLE pk_identity_by_default (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100)
);

-- 6. 默认值+序列
CREATE SEQUENCE seq_default_start;
CREATE TABLE pk_default_seq (
    id NUMBER DEFAULT seq_default_start.NEXTVAL PRIMARY KEY,
    name VARCHAR2(100)
);
-- 7. 主键与外键关联测试
CREATE TABLE pk_parent (
    parent_id       NUMBER PRIMARY KEY,
    parent_name     VARCHAR2(100)
);

CREATE TABLE pk_child (
    child_id        NUMBER PRIMARY KEY,
    parent_id       NUMBER,
    child_name      VARCHAR2(100),
    CONSTRAINT fk_child_parent FOREIGN KEY (parent_id) REFERENCES pk_parent(parent_id)
);

-- 8. 主键与唯一约束组合
CREATE TABLE pk_unique_combined (
    id              NUMBER PRIMARY KEY,
    user_id         VARCHAR2(50) UNIQUE,
    phone           VARCHAR2(20) UNIQUE,
    address         VARCHAR2(500)
);

-- 9. 主键使用CHAR类型
CREATE TABLE pk_char_type (
    code            CHAR(10) PRIMARY KEY,
    description     VARCHAR2(200),
    active          VARCHAR2(1) DEFAULT 'Y'
);

-- 10. 主键使用VARCHAR2类型
CREATE TABLE pk_varchar_type (
    uuid            VARCHAR2(36) PRIMARY KEY,
    data            CLOB,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 11. IDENTITY是主键
CREATE TABLE pk_identity_as_pk (
    id              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100),
    description     VARCHAR2(500)
);

-- 12. IDENTITY不是主键（仅自动生成，但主键由其他列承担）
CREATE TABLE pk_identity_not_pk (
    id              NUMBER(19) GENERATED ALWAYS AS IDENTITY NOT NULL,
    code            VARCHAR2(50) PRIMARY KEY,
    name            VARCHAR2(100)
);

-- 13. IDENTITY是复合主键一部分
CREATE TABLE pk_identity_composite_pk (
    id_part1        NUMBER(19) GENERATED ALWAYS AS IDENTITY,
    id_part2        NUMBER,
    name            VARCHAR2(100),
    PRIMARY KEY (id_part1, id_part2)
);

-- 插入测试数据
INSERT INTO pk_single_column (id, name, email) VALUES (1, 'Alice', 'alice@example.com');
INSERT INTO pk_single_column (id, name, email) VALUES (2, 'Bob', 'bob@example.com');
INSERT INTO pk_single_column (id, name, email) VALUES (3, 'Charlie', 'charlie@example.com');

INSERT INTO pk_composite (department_id, employee_id, name) VALUES (1, 101, 'David');
INSERT INTO pk_composite (department_id, employee_id, name) VALUES (1, 102, 'Eve');
INSERT INTO pk_composite (department_id, employee_id, name) VALUES (2, 201, 'Frank');

INSERT INTO pk_sequence (id, product_name, price, stock) VALUES (seq_pk_sequence.NEXTVAL, 'Product A', 100.00, 100);
INSERT INTO pk_sequence (id, product_name, price, stock) VALUES (seq_pk_sequence.NEXTVAL, 'Product B', 200.00, 50);
INSERT INTO pk_sequence (id, product_name, price, stock) VALUES (seq_pk_sequence.NEXTVAL, 'Product C', 150.00, 75);

INSERT INTO pk_identity (username, password_hash) VALUES ('user1', 'hash123');
INSERT INTO pk_identity (username, password_hash) VALUES ('user2', 'hash456');

INSERT INTO pk_identity_by_default (name) VALUES ('Identity Default A');
INSERT INTO pk_identity_by_default (name) VALUES ('Identity Default B');
INSERT INTO pk_identity_by_default (name) VALUES ('Identity Default C');

INSERT INTO pk_default_seq (name) VALUES ('Default Seq A');
INSERT INTO pk_default_seq (name) VALUES ('Default Seq B');
INSERT INTO pk_default_seq (name) VALUES ('Default Seq C');

INSERT INTO pk_parent (parent_id, parent_name) VALUES (1, 'Parent A');
INSERT INTO pk_parent (parent_id, parent_name) VALUES (2, 'Parent B');
INSERT INTO pk_child (child_id, parent_id, child_name) VALUES (1001, 1, 'Child A1');
INSERT INTO pk_child (child_id, parent_id, child_name) VALUES (1002, 1, 'Child A2');
INSERT INTO pk_child (child_id, parent_id, child_name) VALUES (1003, 2, 'Child B1');

INSERT INTO pk_unique_combined (id, user_id, phone) VALUES (1, 'user001', '13800138001');
INSERT INTO pk_unique_combined (id, user_id, phone) VALUES (2, 'user002', '13800138002');

INSERT INTO pk_char_type (code, description) VALUES ('CODE000001', 'Type A');
INSERT INTO pk_char_type (code, description) VALUES ('CODE000002', 'Type B');

INSERT INTO pk_varchar_type (uuid, data) VALUES ('550e8400-e29b-41d4-a716-446655440000', 'Sample data for UUID key');

INSERT INTO pk_identity_as_pk (name, description) VALUES ('Test A', 'IDENTITY as primary key');
INSERT INTO pk_identity_as_pk (name, description) VALUES ('Test B', 'IDENTITY as primary key');

INSERT INTO pk_identity_not_pk (code, name) VALUES ('CODE001', 'IDENTITY not primary key');
INSERT INTO pk_identity_not_pk (code, name) VALUES ('CODE002', 'IDENTITY not primary key');

INSERT INTO pk_identity_composite_pk (id_part2, name) VALUES (1, 'Composite IDENTITY part 1');
INSERT INTO pk_identity_composite_pk (id_part2, name) VALUES (2, 'Composite IDENTITY part 2');

COMMIT;
