
-- 场景1：标准默认序列
CREATE SEQUENCE normal_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
CACHE 20;

-- 场景2：循环序列（修复 ORA-04013：必须 NOCACHE）
CREATE SEQUENCE cycle_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 5
CYCLE
NOCACHE;  -- 关键修复

-- 场景3：带最大值、不循环
CREATE SEQUENCE maxvalue_seq
START WITH 1
INCREMENT BY 5
MAXVALUE 50
NOCYCLE;

-- 场景4：负数最小值序列
CREATE SEQUENCE minvalue_neg_seq
MINVALUE -100
START WITH -10
INCREMENT BY 1
MAXVALUE 100
NOCYCLE;

-- 场景5：递减序列（修复 ORA-04004：必须加 MAXVALUE）
CREATE SEQUENCE increment_neg_seq
START WITH 100
INCREMENT BY -10
MINVALUE 0
MAXVALUE 100  -- 关键修复
NOCYCLE;

CREATE SEQUENCE increment_neg_cycle_seq
START WITH 10
INCREMENT BY -1
MINVALUE 1
MAXVALUE 10
CYCLE
NOCACHE;
-- 场景6：无缓存序列
CREATE SEQUENCE nocache_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 场景7：RAC 强制排序序列
CREATE SEQUENCE order_seq
START WITH 1
INCREMENT BY 1
CACHE 10
ORDER;

-- 场景8：大起始值序列
CREATE SEQUENCE start_from_1000_seq
START WITH 1000
INCREMENT BY 1
MAXVALUE 999999999
NOCYCLE;
