# global settings
# 是否记录进度
isDumpJson: true
# 进度文件地址
statusDir: /**/**
# 是否删除迁移成功的csv文件
isDeleteCsv: true
# 是否保留原有schema
isKeepExistingSchema: false
# 目标端数据库配置
ogConn:
  host: "192.168.0.2"
  port: 5432
  user: "username"
  password: "password"
  database: "database"
  charset: "utf8"
  params:
sourceConfig:
  # 查询表的线程数
  readerNum: 4
  # 写表的线程数
  writerNum: 4
  # 全量数据文件大小划分配置，支持K、M、G大小配置，没有单位默认按照M单位处理，默认值为 2M
  fileSize: 2M
  # 源端数据库连接信息
  dbConn:
    host: "192.168.0.1"
    port: "1433"
    user: "username"
    password: "password"
    database: "database"
    charset: 'utf8'
    connectTimeout: 10
  # schema映射关系
  schemaMappings:
  #  schema1: ogschema1
  #  schema2: ogschema2
  # 复制表白名单，不配置则复制所有表
  limitTables:
  # - schema1.table1
  # - schema1.table2
  # - schema2.table3
  # 复制表黑名单
  skipTables:
  # - schema1.table4
  # 目标端建表添加with(segment=on)选项；opengauss迁移至openGauss时，源端表有with(segment=on)，迁移时会默认添加）：
  addSegmentTables:
  # - schema1.table1
  # - schema2.table3
  csvDir: /**/**
  # sqlserver中time,datetime2和datetimeoffset类型精度为0-7，openGauss中对应类型精度为0-6，可能会有精度损失，该参数控制是否迁移这三种类型
  isTimeMigrate: true
  # sqlserver中money和smallmoney数据类型精确到它们所代表的货币单位的万分之一，openGauss的money类型精确到它们所代表的货币单位的百分之一，该参数控制是否迁移货币类型
  isMoneyMigrate: true
  # 是否迁移源库的默认值到openGauss
  isMigrateDefaultValue: Yes
  # 是否记录快照
  isRecordSnapshot: Yes
  # postgres逻辑复制槽名称
  slotName: "test_slot"
  # 创建逻辑复制槽插件名称(版本大于10时优选pgoutput，wal2json次之)
  pluginName: "pgoutput"