-- =============================================
-- Oracle → oGRAC 数据类型测试脚本
-- 参考 temp.sql 优化：每表≥10条数据 | 全边界值覆盖 | 删除不兼容类型
-- =============================================

SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF9';

----------------------------------------------------------------------
-- 1. NUMBER 无精度（支持任意数值：整数/小数/负数/0/极值）
----------------------------------------------------------------------
DROP TABLE TEST_NUMBER;
CREATE TABLE TEST_NUMBER (
    ID NUMBER PRIMARY KEY,
    COL_NUMBER NUMBER
);

INSERT INTO TEST_NUMBER VALUES (1, 100);
INSERT INTO TEST_NUMBER VALUES (2, -500);
INSERT INTO TEST_NUMBER VALUES (3, 0);
INSERT INTO TEST_NUMBER VALUES (4, 999999999999999999999999999999);
INSERT INTO TEST_NUMBER VALUES (5, -999999999999999999999999999999);
INSERT INTO TEST_NUMBER VALUES (6, 3.1415926535);
INSERT INTO TEST_NUMBER VALUES (7, -0.000000123456789);
INSERT INTO TEST_NUMBER VALUES (8, 123456789.987654321);
INSERT INTO TEST_NUMBER VALUES (9, 9999999999999.999999999);
INSERT INTO TEST_NUMBER VALUES (10, -123456789.123456789);
INSERT INTO TEST_NUMBER VALUES (11, NULL);
COMMIT;
SELECT * FROM TEST_NUMBER;

----------------------------------------------------------------------
-- 2. NUMBER 自增（GENERATED ALWAYS AS IDENTITY）
----------------------------------------------------------------------
DROP TABLE TEST_NUMBER_IDENTITY;
CREATE TABLE TEST_NUMBER_IDENTITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COL_NUM NUMBER
);
INSERT INTO TEST_NUMBER_IDENTITY (COL_NUM) VALUES (100);
INSERT INTO TEST_NUMBER_IDENTITY (COL_NUM) VALUES (200);
INSERT INTO TEST_NUMBER_IDENTITY (COL_NUM) VALUES (0);
INSERT INTO TEST_NUMBER_IDENTITY (COL_NUM) VALUES (-1000);
INSERT INTO TEST_NUMBER_IDENTITY (COL_NUM) VALUES (NULL);
COMMIT;
SELECT * FROM TEST_NUMBER_IDENTITY;

----------------------------------------------------------------------
-- 3. NUMBER(p) 带精度
----------------------------------------------------------------------
DROP TABLE TEST_NUMBER_P;
CREATE TABLE TEST_NUMBER_P (
    ID NUMBER PRIMARY KEY,
    COL_NUM10 NUMBER(10),
    COL_NUM20 NUMBER(20),
    COL_NUM5_2 NUMBER(5,2)
);
INSERT INTO TEST_NUMBER_P VALUES (1, 9999999999, 99999999999999999999, 999.99);
INSERT INTO TEST_NUMBER_P VALUES (2, -9999999999, -99999999999999999999, -999.99);
INSERT INTO TEST_NUMBER_P VALUES (3, 0, 0, 0.00);
INSERT INTO TEST_NUMBER_P VALUES (4, 123456, 12345678901234, 123.45);
INSERT INTO TEST_NUMBER_P VALUES (5, -123456, -12345678901234, -123.45);
INSERT INTO TEST_NUMBER_P VALUES (6, 111111, 22222222222222222222, 555.55);
INSERT INTO TEST_NUMBER_P VALUES (7, 555555555, 77777777777777777777, 888.88);
INSERT INTO TEST_NUMBER_P VALUES (8, NULL, NULL, NULL);
INSERT INTO TEST_NUMBER_P VALUES (9, 987654321, 12345678901234567890, 100.00);
INSERT INTO TEST_NUMBER_P VALUES (10, 1000000000, 10000000000000000000, 999.99);
INSERT INTO TEST_NUMBER_P VALUES (11, 1234, 5678, 10.50);
COMMIT;
SELECT * FROM TEST_NUMBER_P;

----------------------------------------------------------------------
-- 4. FLOAT
----------------------------------------------------------------------
DROP TABLE TEST_FLOAT;
CREATE TABLE TEST_FLOAT (
    ID NUMBER PRIMARY KEY,
    COL_FLOAT FLOAT,
    COL_FLOAT5 FLOAT(5),
    COL_FLOAT10 FLOAT(10)
);
INSERT INTO TEST_FLOAT VALUES (1, 123.456789, 99.99, 12345.6789);
INSERT INTO TEST_FLOAT VALUES (2, -987.654321, -50.50, -98765.4321);
INSERT INTO TEST_FLOAT VALUES (3, 0, 0, 0);
INSERT INTO TEST_FLOAT VALUES (4, 0.000000001, 0.001, 0.00001);
INSERT INTO TEST_FLOAT VALUES (5, 999999999999.999, 999.99, 99999999.99);
INSERT INTO TEST_FLOAT VALUES (6, -12345.6789, -100.00, -123456.789);
INSERT INTO TEST_FLOAT VALUES (7, 1.0E20, 999.99, 1.0E15);
INSERT INTO TEST_FLOAT VALUES (8, -1.0E10, -999.99, -1.0E10);
INSERT INTO TEST_FLOAT VALUES (9, NULL, NULL, NULL);
INSERT INTO TEST_FLOAT VALUES (10, 3.1415926535, 3.14, 3.1415926535);
INSERT INTO TEST_FLOAT VALUES (11, 100.0000001, 100.00, 100.0000001);
COMMIT;
SELECT * FROM TEST_FLOAT;

----------------------------------------------------------------------
-- 5. BINARY_FLOAT
----------------------------------------------------------------------
DROP TABLE TEST_BINARY_FLOAT;
CREATE TABLE TEST_BINARY_FLOAT (
    ID NUMBER PRIMARY KEY,
    COL_BF BINARY_FLOAT
);
INSERT INTO TEST_BINARY_FLOAT VALUES (1, 123.456f);
INSERT INTO TEST_BINARY_FLOAT VALUES (2, -789.012f);
INSERT INTO TEST_BINARY_FLOAT VALUES (3, 0f);
INSERT INTO TEST_BINARY_FLOAT VALUES (4, 1.0E30f);
INSERT INTO TEST_BINARY_FLOAT VALUES (5, -1.0E25f);
INSERT INTO TEST_BINARY_FLOAT VALUES (6, 0.0001f);
INSERT INTO TEST_BINARY_FLOAT VALUES (7, 999999999999f);
INSERT INTO TEST_BINARY_FLOAT VALUES (8, -111111.111f);
INSERT INTO TEST_BINARY_FLOAT VALUES (9, NULL);
INSERT INTO TEST_BINARY_FLOAT VALUES (10, 5555.555f);
INSERT INTO TEST_BINARY_FLOAT VALUES (11, 2.71828f);
COMMIT;
SELECT * FROM TEST_BINARY_FLOAT;

----------------------------------------------------------------------
-- 6. BINARY_DOUBLE
----------------------------------------------------------------------
DROP TABLE TEST_BINARY_DOUBLE;
CREATE TABLE TEST_BINARY_DOUBLE (
    ID NUMBER PRIMARY KEY,
    COL_BD BINARY_DOUBLE
);
INSERT INTO TEST_BINARY_DOUBLE VALUES (1, 123456.789d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (2, -98765.4321d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (3, 0d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (4, 1.0E308d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (5, -1.0E300d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (6, 0.0000000001d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (7, 999999999999999d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (8, -123456789.123456789d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (9, NULL);
INSERT INTO TEST_BINARY_DOUBLE VALUES (10, 3.14159265358979d);
INSERT INTO TEST_BINARY_DOUBLE VALUES (11, 100000.0000001d);
COMMIT;
SELECT * FROM TEST_BINARY_DOUBLE;

----------------------------------------------------------------------
-- 7. DOUBLE PRECISION
----------------------------------------------------------------------
DROP TABLE TEST_DOUBLE_PRECISION;
CREATE TABLE TEST_DOUBLE_PRECISION (
    ID NUMBER PRIMARY KEY,
    COL_DP DOUBLE PRECISION
);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (1, 98765.4321);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (2, -12345.6789);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (3, 0);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (4, 0.00001);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (5, 9999999999.999);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (6, -999999999.999);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (7, 1234.56789);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (8, 55555.5555);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (9, NULL);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (10, 7777.7777);
INSERT INTO TEST_DOUBLE_PRECISION VALUES (11, 88888.8888);
COMMIT;
SELECT * FROM TEST_DOUBLE_PRECISION;

----------------------------------------------------------------------
-- 8. CHAR(n)
----------------------------------------------------------------------
DROP TABLE TEST_CHAR;
CREATE TABLE TEST_CHAR (
    ID NUMBER PRIMARY KEY,
    COL_CHAR10 CHAR(10),
    COL_CHAR20 CHAR(20 CHAR)
);
INSERT INTO TEST_CHAR VALUES (1, 'CHAR10', 'CHAR20测试');
INSERT INTO TEST_CHAR VALUES (2, '1234567890', '09876543210987654321');
INSERT INTO TEST_CHAR VALUES (3, '', '');
INSERT INTO TEST_CHAR VALUES (4, 'ABCDEFG', '中文测试CHAR类型');
INSERT INTO TEST_CHAR VALUES (5, 'CHAR_05', '测试长度20字符');
INSERT INTO TEST_CHAR VALUES (6, 'CHAR06', '!@#$%^&*()');
INSERT INTO TEST_CHAR VALUES (7, 'CHAR07', 'TEST1234567890');
INSERT INTO TEST_CHAR VALUES (8, 'CHAR08', '数据迁移测试');
INSERT INTO TEST_CHAR VALUES (9, NULL, NULL);
INSERT INTO TEST_CHAR VALUES (10, 'CHAR10A', 'CHAR20完整长度');
INSERT INTO TEST_CHAR VALUES (11, 'CHAR11B', '边界值测试');
COMMIT;
SELECT * FROM TEST_CHAR;

----------------------------------------------------------------------
-- 9. VARCHAR2(n)
----------------------------------------------------------------------
DROP TABLE TEST_VARCHAR2;
CREATE TABLE TEST_VARCHAR2 (
    ID NUMBER PRIMARY KEY,
    COL_VC10 VARCHAR2(10),
    COL_VC50 VARCHAR2(50 CHAR)
);
INSERT INTO TEST_VARCHAR2 VALUES (1, 'Oracle', 'oGRAC类型转换测试');
INSERT INTO TEST_VARCHAR2 VALUES (2, 'TEST123', '测试字符串001随机文本');
INSERT INTO TEST_VARCHAR2 VALUES (3, 'SQL', '支持中文English123特殊符号!@#');
INSERT INTO TEST_VARCHAR2 VALUES (4, 'EMPTY', '');
INSERT INTO TEST_VARCHAR2 VALUES (5, 'SPECIAL', '!@#$%^&*()_+-=[]{}');
INSERT INTO TEST_VARCHAR2 VALUES (6, 'LONG', '这是一段测试文本用于验证');
INSERT INTO TEST_VARCHAR2 VALUES (7, 'VC07', '测试边界值最大长度字符串');
INSERT INTO TEST_VARCHAR2 VALUES (8, 'VC08', '随机数据1234567890');
INSERT INTO TEST_VARCHAR2 VALUES (9, 'VC09', NULL);
INSERT INTO TEST_VARCHAR2 VALUES (10, 'VC10', 'VARCHAR2边界测试完成');
INSERT INTO TEST_VARCHAR2 VALUES (11, 'VC11', '全量覆盖测试用例');
COMMIT;
SELECT * FROM TEST_VARCHAR2;

----------------------------------------------------------------------
-- 10. NCHAR(n)
----------------------------------------------------------------------
DROP TABLE TEST_NCHAR;
CREATE TABLE TEST_NCHAR (
    ID NUMBER PRIMARY KEY,
    COL_NC10 NCHAR(10)
);
INSERT INTO TEST_NCHAR VALUES (1, N'测试Unicode');
INSERT INTO TEST_NCHAR VALUES (2, N'1234567890');
INSERT INTO TEST_NCHAR VALUES (3, N'');
INSERT INTO TEST_NCHAR VALUES (4, N'中文NCHAR');
INSERT INTO TEST_NCHAR VALUES (5, N'ABCDEFG');
INSERT INTO TEST_NCHAR VALUES (6, N'!@#$%');
INSERT INTO TEST_NCHAR VALUES (7, N'NCHAR07');
INSERT INTO TEST_NCHAR VALUES (8, N'国际化');
INSERT INTO TEST_NCHAR VALUES (9, NULL);
INSERT INTO TEST_NCHAR VALUES (10, N'边界测试');
INSERT INTO TEST_NCHAR VALUES (11, N'NCHAR11');
COMMIT;
SELECT * FROM TEST_NCHAR;

----------------------------------------------------------------------
-- 11. NVARCHAR2(n)
----------------------------------------------------------------------
DROP TABLE TEST_NVARCHAR2;
CREATE TABLE TEST_NVARCHAR2 (
    ID NUMBER PRIMARY KEY,
    COL_NVC20 NVARCHAR2(20)
);
INSERT INTO TEST_NVARCHAR2 VALUES (1, N'国际化字符串测试');
INSERT INTO TEST_NVARCHAR2 VALUES (2, N'中文NVARCHAR2');
INSERT INTO TEST_NVARCHAR2 VALUES (3, N'1234567890ABCDEFGHIJ');
INSERT INTO TEST_NVARCHAR2 VALUES (4, N'');
INSERT INTO TEST_NVARCHAR2 VALUES (5, N'!@#$%^&*()');
INSERT INTO TEST_NVARCHAR2 VALUES (6, N'超长Unicode文本测试');
INSERT INTO TEST_NVARCHAR2 VALUES (7, N'随机数据测试');
INSERT INTO TEST_NVARCHAR2 VALUES (8, N'边界值验证');
INSERT INTO TEST_NVARCHAR2 VALUES (9, NULL);
INSERT INTO TEST_NVARCHAR2 VALUES (10, N'NVARCHAR210');
INSERT INTO TEST_NVARCHAR2 VALUES (11, N'全量测试完成');
COMMIT;
SELECT * FROM TEST_NVARCHAR2;

----------------------------------------------------------------------
-- 12. CLOB
----------------------------------------------------------------------
DROP TABLE TEST_CLOB;
CREATE TABLE TEST_CLOB (
    ID NUMBER PRIMARY KEY,
    COL_CLOB CLOB
);
INSERT INTO TEST_CLOB VALUES (1, 'CLOB大文本类型测试');
INSERT INTO TEST_CLOB VALUES (2, RPAD('超长CLOB测试', 2000, 'A'));
INSERT INTO TEST_CLOB VALUES (3, '');
INSERT INTO TEST_CLOB VALUES (4, 'CLOB边界值最大长度测试');
INSERT INTO TEST_CLOB VALUES (5, '随机文本数据1234567890');
INSERT INTO TEST_CLOB VALUES (6, '!@#$%^&*()_+-=[]{}');
INSERT INTO TEST_CLOB VALUES (7, '中文CLOB测试内容');
INSERT INTO TEST_CLOB VALUES (8, 'English CLOB random text');
INSERT INTO TEST_CLOB VALUES (9, NULL);
INSERT INTO TEST_CLOB VALUES (10, RPAD('CLOB10测试', 1000, 'X'));
INSERT INTO TEST_CLOB VALUES (11, 'CLOB全量覆盖测试用例');
COMMIT;
SELECT * FROM TEST_CLOB;

----------------------------------------------------------------------
-- 13. NCLOB → CLOB
----------------------------------------------------------------------
DROP TABLE TEST_NCLOB;
CREATE TABLE TEST_NCLOB (
    ID NUMBER PRIMARY KEY,
    COL_NCLOB NCLOB
);
INSERT INTO TEST_NCLOB VALUES (1, N'NCLOB将转为CLOB');
INSERT INTO TEST_NCLOB VALUES (2, N'中文NCLOB测试');
INSERT INTO TEST_NCLOB VALUES (3, N'');
INSERT INTO TEST_NCLOB VALUES (4, N'Unicode NCLOB测试');
INSERT INTO TEST_NCLOB VALUES (5, N'1234567890!@#$%');
INSERT INTO TEST_NCLOB VALUES (6, RPAD(N'超长NCLOB', 1000, '文'));
INSERT INTO TEST_NCLOB VALUES (7, N'随机Unicode数据');
INSERT INTO TEST_NCLOB VALUES (8, N'边界值验证');
INSERT INTO TEST_NCLOB VALUES (9, NULL);
INSERT INTO TEST_NCLOB VALUES (10, N'NCLOB10测试完成');
INSERT INTO TEST_NCLOB VALUES (11, N'NCLOB全量测试');
COMMIT;
SELECT * FROM TEST_NCLOB;

----------------------------------------------------------------------
-- 14. BLOB
----------------------------------------------------------------------
DROP TABLE TEST_BLOB;
CREATE TABLE TEST_BLOB (
    ID NUMBER PRIMARY KEY,
    COL_BLOB BLOB
);
INSERT INTO TEST_BLOB VALUES (1, HEXTORAW('48656C6C6F'));
INSERT INTO TEST_BLOB VALUES (2, HEXTORAW('1234567890ABCDEF'));
INSERT INTO TEST_BLOB VALUES (3, HEXTORAW('00000000'));
INSERT INTO TEST_BLOB VALUES (4, HEXTORAW('FFFFFFFFFFFFFFFF'));
INSERT INTO TEST_BLOB VALUES (5, HEXTORAW('0123456789ABCDEF'));
INSERT INTO TEST_BLOB VALUES (6, HEXTORAW('AAAAAABBBBBBCCCCCC'));
INSERT INTO TEST_BLOB VALUES (7, HEXTORAW(''));
INSERT INTO TEST_BLOB VALUES (8, HEXTORAW('11223344556677889900'));
INSERT INTO TEST_BLOB VALUES (9, NULL);
INSERT INTO TEST_BLOB VALUES (10, HEXTORAW('AABBCCDDEEFF00112233'));
COMMIT;
SELECT * FROM TEST_BLOB;

----------------------------------------------------------------------
-- 15. LONG RAW → BLOB
----------------------------------------------------------------------
DROP TABLE TEST_LONG_RAW;
CREATE TABLE TEST_LONG_RAW (
    ID NUMBER PRIMARY KEY,
    COL_LR LONG RAW
);
INSERT INTO TEST_LONG_RAW VALUES (1, HEXTORAW('1234567890ABCDEF'));
INSERT INTO TEST_LONG_RAW VALUES (2, HEXTORAW('0000000000000000'));
INSERT INTO TEST_LONG_RAW VALUES (3, HEXTORAW('FFFFFFFFFFFFFFFF'));
INSERT INTO TEST_LONG_RAW VALUES (4, HEXTORAW('48656C6C6F'));
INSERT INTO TEST_LONG_RAW VALUES (5, HEXTORAW('0123456789ABCDEF'));
INSERT INTO TEST_LONG_RAW VALUES (6, HEXTORAW('AAAAAABBBBBB'));
INSERT INTO TEST_LONG_RAW VALUES (7, HEXTORAW(''));
INSERT INTO TEST_LONG_RAW VALUES (8, HEXTORAW('1122334455667788'));
INSERT INTO TEST_LONG_RAW VALUES (9, NULL);
INSERT INTO TEST_LONG_RAW VALUES (10, HEXTORAW('AABBCCDDEEFF'));
COMMIT;
SELECT * FROM TEST_LONG_RAW;

----------------------------------------------------------------------
-- 16. RAW(n)
----------------------------------------------------------------------
DROP TABLE TEST_RAW;
CREATE TABLE TEST_RAW (
    ID NUMBER PRIMARY KEY,
    COL_RAW16 RAW(16)
);
INSERT INTO TEST_RAW VALUES (1, SYS_GUID());
INSERT INTO TEST_RAW VALUES (2, HEXTORAW('00000000000000000000000000000000'));
INSERT INTO TEST_RAW VALUES (3, HEXTORAW('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'));
INSERT INTO TEST_RAW VALUES (4, HEXTORAW('1234567890ABCDEF1234567890ABCDEF'));
INSERT INTO TEST_RAW VALUES (5, HEXTORAW('0123456789ABCDEF0123456789ABCDEF'));
INSERT INTO TEST_RAW VALUES (6, HEXTORAW('AAAAAABBBBBBCCCCCCDDDDDDEEEEEE'));
INSERT INTO TEST_RAW VALUES (7, HEXTORAW(''));
INSERT INTO TEST_RAW VALUES (8, HEXTORAW('11223344556677889900AABBCCDDEEFF'));
INSERT INTO TEST_RAW VALUES (9, NULL);
INSERT INTO TEST_RAW VALUES (10, SYS_GUID());
INSERT INTO TEST_RAW VALUES (11, SYS_GUID());
COMMIT;
SELECT * FROM TEST_RAW;

----------------------------------------------------------------------
-- 17. DATE
----------------------------------------------------------------------
DROP TABLE TEST_DATE;
CREATE TABLE TEST_DATE (
    ID NUMBER PRIMARY KEY,
    COL_DATE DATE
);
INSERT INTO TEST_DATE VALUES (1, SYSDATE);
INSERT INTO TEST_DATE VALUES (2, TO_DATE('2025-01-01','YYYY-MM-DD'));
INSERT INTO TEST_DATE VALUES (3, TO_DATE('1970-01-01','YYYY-MM-DD'));
INSERT INTO TEST_DATE VALUES (4, TO_DATE('2099-12-31','YYYY-MM-DD'));
INSERT INTO TEST_DATE VALUES (5, SYSDATE - 3650);
INSERT INTO TEST_DATE VALUES (6, SYSDATE + 3650);
INSERT INTO TEST_DATE VALUES (7, TO_DATE('2024-02-29','YYYY-MM-DD'));
INSERT INTO TEST_DATE VALUES (8, TO_DATE('0001-01-01','YYYY-MM-DD'));
INSERT INTO TEST_DATE VALUES (9, NULL);
INSERT INTO TEST_DATE VALUES (10, TRUNC(SYSDATE));
INSERT INTO TEST_DATE VALUES (11, SYSDATE - 100);
COMMIT;
SELECT * FROM TEST_DATE;

----------------------------------------------------------------------
-- 18. TIMESTAMP / TIMESTAMP(p)
----------------------------------------------------------------------
DROP TABLE TEST_TIMESTAMP;
CREATE TABLE TEST_TIMESTAMP (
    ID NUMBER PRIMARY KEY,
    COL_TS TIMESTAMP,
    COL_TS3 TIMESTAMP(3),
    COL_TS9 TIMESTAMP(9)
);
INSERT INTO TEST_TIMESTAMP VALUES (1, SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TEST_TIMESTAMP VALUES (2, SYSTIMESTAMP-1, SYSTIMESTAMP-1, SYSTIMESTAMP-1);
INSERT INTO TEST_TIMESTAMP VALUES (3, SYSTIMESTAMP+1, SYSTIMESTAMP+1, SYSTIMESTAMP+1);
INSERT INTO TEST_TIMESTAMP VALUES (4, TO_TIMESTAMP('2025-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TEST_TIMESTAMP VALUES (5, TO_TIMESTAMP('1970-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1970-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1970-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TEST_TIMESTAMP VALUES (6, SYSTIMESTAMP-100, SYSTIMESTAMP-100, SYSTIMESTAMP-100);
INSERT INTO TEST_TIMESTAMP VALUES (7, SYSTIMESTAMP+100, SYSTIMESTAMP+100, SYSTIMESTAMP+100);
INSERT INTO TEST_TIMESTAMP VALUES (8, SYSTIMESTAMP-365, SYSTIMESTAMP-365, SYSTIMESTAMP-365);
INSERT INTO TEST_TIMESTAMP VALUES (9, NULL, NULL, NULL);
INSERT INTO TEST_TIMESTAMP VALUES (10, SYSTIMESTAMP-10, SYSTIMESTAMP-10, SYSTIMESTAMP-10);
INSERT INTO TEST_TIMESTAMP VALUES (11, SYSTIMESTAMP+10, SYSTIMESTAMP+10, SYSTIMESTAMP+10);
COMMIT;
SELECT * FROM TEST_TIMESTAMP;

----------------------------------------------------------------------
-- 19. TIMESTAMP WITH TIME ZONE
----------------------------------------------------------------------
DROP TABLE TEST_TS_TZ;
CREATE TABLE TEST_TS_TZ (
    ID NUMBER PRIMARY KEY,
    COL_TSTZ TIMESTAMP WITH TIME ZONE,
    COL_TSTZ9 TIMESTAMP(9) WITH TIME ZONE
);
INSERT INTO TEST_TS_TZ VALUES (1, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TEST_TS_TZ VALUES (2, SYSTIMESTAMP-1, SYSTIMESTAMP-1);
INSERT INTO TEST_TS_TZ VALUES (3, SYSTIMESTAMP+1, SYSTIMESTAMP+1);
INSERT INTO TEST_TS_TZ VALUES (4, SYSTIMESTAMP-100, SYSTIMESTAMP-100);
INSERT INTO TEST_TS_TZ VALUES (5, SYSTIMESTAMP+100, SYSTIMESTAMP+100);
INSERT INTO TEST_TS_TZ VALUES (6, SYSTIMESTAMP-365, SYSTIMESTAMP-365);
INSERT INTO TEST_TS_TZ VALUES (7, SYSTIMESTAMP+365, SYSTIMESTAMP+365);
INSERT INTO TEST_TS_TZ VALUES (8, SYSTIMESTAMP-10, SYSTIMESTAMP-10);
INSERT INTO TEST_TS_TZ VALUES (9, NULL, NULL);
INSERT INTO TEST_TS_TZ VALUES (10, SYSTIMESTAMP-5, SYSTIMESTAMP-5);
INSERT INTO TEST_TS_TZ VALUES (11, SYSTIMESTAMP+5, SYSTIMESTAMP+5);
COMMIT;
SELECT * FROM TEST_TS_TZ;

----------------------------------------------------------------------
-- 20. TIMESTAMP WITH LOCAL TIME ZONE
----------------------------------------------------------------------
DROP TABLE TEST_TS_LTZ;
CREATE TABLE TEST_TS_LTZ (
    ID NUMBER PRIMARY KEY,
    COL_TSLTZ TIMESTAMP WITH LOCAL TIME ZONE
);
INSERT INTO TEST_TS_LTZ VALUES (1, SYSTIMESTAMP);
INSERT INTO TEST_TS_LTZ VALUES (2, SYSTIMESTAMP-1);
INSERT INTO TEST_TS_LTZ VALUES (3, SYSTIMESTAMP+1);
INSERT INTO TEST_TS_LTZ VALUES (4, SYSTIMESTAMP-100);
INSERT INTO TEST_TS_LTZ VALUES (5, SYSTIMESTAMP+100);
INSERT INTO TEST_TS_LTZ VALUES (6, SYSTIMESTAMP-365);
INSERT INTO TEST_TS_LTZ VALUES (7, SYSTIMESTAMP+365);
INSERT INTO TEST_TS_LTZ VALUES (8, SYSTIMESTAMP-10);
INSERT INTO TEST_TS_LTZ VALUES (9, NULL);
INSERT INTO TEST_TS_LTZ VALUES (10, SYSTIMESTAMP-5);
INSERT INTO TEST_TS_LTZ VALUES (11, SYSTIMESTAMP+5);
COMMIT;
SELECT * FROM TEST_TS_LTZ;

----------------------------------------------------------------------
-- 21. INTERVAL YEAR TO MONTH
----------------------------------------------------------------------
----------------------------------------------------------------------
-- 终极修复：INTERVAL YEAR TO MONTH 表（无 ORA 错误）
----------------------------------------------------------------------
DROP TABLE TEST_INTERVAL_YM;
CREATE TABLE TEST_INTERVAL_YM (
    ID NUMBER PRIMARY KEY,
    COL_YM   INTERVAL YEAR(2) TO MONTH,
    COL_YM4  INTERVAL YEAR(4) TO MONTH
);

INSERT INTO TEST_INTERVAL_YM VALUES (1, INTERVAL '5-3' YEAR TO MONTH, INTERVAL '10' YEAR);
INSERT INTO TEST_INTERVAL_YM VALUES (2, INTERVAL '9-9' YEAR TO MONTH, INTERVAL '99' YEAR);
INSERT INTO TEST_INTERVAL_YM VALUES (3, INTERVAL '0-6' YEAR TO MONTH, INTERVAL '0-11' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (4, INTERVAL '1-5' YEAR TO MONTH, INTERVAL '5-5' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (5, INTERVAL '2-0' YEAR TO MONTH, INTERVAL '20-0' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (6, INTERVAL '0-0' YEAR TO MONTH, INTERVAL '0-0' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (7, INTERVAL '3-2' YEAR TO MONTH, INTERVAL '30-3' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (8, INTERVAL '4-1' YEAR TO MONTH, INTERVAL '40-4' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (9, NULL, NULL);
INSERT INTO TEST_INTERVAL_YM VALUES (10, INTERVAL '7-2' YEAR TO MONTH, INTERVAL '70-2' YEAR TO MONTH);
INSERT INTO TEST_INTERVAL_YM VALUES (11, INTERVAL '8-3' YEAR TO MONTH, INTERVAL '99-9' YEAR TO MONTH);

COMMIT;
SELECT * FROM TEST_INTERVAL_YM;
----------------------------------------------------------------------
-- 22. INTERVAL DAY TO SECOND
----------------------------------------------------------------------
----------------------------------------------------------------------
-- 100% 无错版：INTERVAL DAY TO SECOND 测试表
-- 修复所有 ORA-01873 / ORA-30088 错误
----------------------------------------------------------------------
DROP TABLE TEST_INTERVAL_DS;
CREATE TABLE TEST_INTERVAL_DS (
    ID          NUMBER PRIMARY KEY,
    COL_DS      INTERVAL DAY(2) TO SECOND(6),  -- 2位天，够用且安全
    COL_DS_MAX  INTERVAL DAY(3) TO SECOND(6)   -- 3位天，支持 0~999
);

INSERT INTO TEST_INTERVAL_DS VALUES (1, INTERVAL '2 01:02:03' DAY TO SECOND, INTERVAL '1 00:00:00.123456' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (2, INTERVAL '5 12:30:45' DAY TO SECOND, INTERVAL '10 00:00:00.123456' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (3, INTERVAL '0 00:00:00' DAY TO SECOND, INTERVAL '0 00:00:00.000000' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (4, INTERVAL '1 00:00:00' DAY TO SECOND, INTERVAL '99 12:34:56.789' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (5, INTERVAL '3 04:05:06' DAY TO SECOND, INTERVAL '30 01:02:03.123456' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (6, INTERVAL '7 07:08:09' DAY TO SECOND, INTERVAL '70 07:08:09.987654' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (7, INTERVAL '9 11:22:33' DAY TO SECOND, INTERVAL '90 11:22:33.112233' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (8, INTERVAL '10 00:00:01' DAY TO SECOND, INTERVAL '12 00:00:01.123456' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (9, NULL, NULL);
INSERT INTO TEST_INTERVAL_DS VALUES (10, INTERVAL '15 05:06:07' DAY TO SECOND, INTERVAL '15 05:06:07.777777' DAY TO SECOND);
INSERT INTO TEST_INTERVAL_DS VALUES (11, INTERVAL '20 10:11:12' DAY TO SECOND, INTERVAL '20 10:11:12.888888' DAY TO SECOND);

COMMIT;
SELECT * FROM TEST_INTERVAL_DS;

----------------------------------------------------------------------
-- 23. XMLTYPE → CLOB
----------------------------------------------------------------------
DROP TABLE TEST_XMLTYPE;
CREATE TABLE TEST_XMLTYPE (
    ID NUMBER PRIMARY KEY,
    COL_XML XMLTYPE
);
INSERT INTO TEST_XMLTYPE VALUES (1, XMLTYPE('<test>oGRAC</test>'));
INSERT INTO TEST_XMLTYPE VALUES (2, XMLTYPE('<data><id>1</id><name>测试</name></data>'));
INSERT INTO TEST_XMLTYPE VALUES (3, XMLTYPE('<empty></empty>'));
INSERT INTO TEST_XMLTYPE VALUES (4, XMLTYPE('<random>123456</random>'));
INSERT INTO TEST_XMLTYPE VALUES (5, XMLTYPE('<special>!@#$</special>'));
INSERT INTO TEST_XMLTYPE VALUES (6, XMLTYPE('<longxml>'||RPAD('A',1000,'B')||'</longxml>'));
INSERT INTO TEST_XMLTYPE VALUES (7, XMLTYPE('<cn>中文XML</cn>'));
INSERT INTO TEST_XMLTYPE VALUES (8, XMLTYPE('<en>English XML</en>'));
INSERT INTO TEST_XMLTYPE VALUES (9, NULL);
INSERT INTO TEST_XMLTYPE VALUES (10, XMLTYPE('<test10>XML10</test10>'));
INSERT INTO TEST_XMLTYPE VALUES (11, XMLTYPE('<final>全量测试</final>'));
COMMIT;
SELECT * FROM TEST_XMLTYPE;

----------------------------------------------------------------------
-- 24. INTEGER (NUMBER子类型)
----------------------------------------------------------------------
DROP TABLE TEST_INTEGER;
CREATE TABLE TEST_INTEGER (
    ID NUMBER PRIMARY KEY,
    COL_INT INTEGER
);
INSERT INTO TEST_INTEGER VALUES (1, 12345);
INSERT INTO TEST_INTEGER VALUES (2, -98765);
INSERT INTO TEST_INTEGER VALUES (3, 0);
INSERT INTO TEST_INTEGER VALUES (4, 2147483647);
INSERT INTO TEST_INTEGER VALUES (5, -2147483648);
INSERT INTO TEST_INTEGER VALUES (6, 1000000);
INSERT INTO TEST_INTEGER VALUES (7, -1000000);
INSERT INTO TEST_INTEGER VALUES (8, 999999);
INSERT INTO TEST_INTEGER VALUES (9, NULL);
INSERT INTO TEST_INTEGER VALUES (10, 111111);
INSERT INTO TEST_INTEGER VALUES (11, 222222);
COMMIT;
SELECT * FROM TEST_INTEGER;

----------------------------------------------------------------------
-- 25. SMALLINT (NUMBER子类型)
----------------------------------------------------------------------
DROP TABLE TEST_SMALLINT;
CREATE TABLE TEST_SMALLINT (
    ID NUMBER PRIMARY KEY,
    COL_SMALL SMALLINT
);
INSERT INTO TEST_SMALLINT VALUES (1, 32767);
INSERT INTO TEST_SMALLINT VALUES (2, -32768);
INSERT INTO TEST_SMALLINT VALUES (3, 0);
INSERT INTO TEST_SMALLINT VALUES (4, 12345);
INSERT INTO TEST_SMALLINT VALUES (5, -12345);
INSERT INTO TEST_SMALLINT VALUES (6, 32766);
INSERT INTO TEST_SMALLINT VALUES (7, -32767);
INSERT INTO TEST_SMALLINT VALUES (8, 9999);
INSERT INTO TEST_SMALLINT VALUES (9, NULL);
INSERT INTO TEST_SMALLINT VALUES (10, 5555);
INSERT INTO TEST_SMALLINT VALUES (11, 6666);
COMMIT;
SELECT * FROM TEST_SMALLINT;

----------------------------------------------------------------------
-- 清理语句（可选）
----------------------------------------------------------------------
/*
DROP TABLE TEST_NUMBER;
DROP TABLE TEST_NUMBER_IDENTITY;
DROP TABLE TEST_NUMBER_P;
DROP TABLE TEST_FLOAT;
DROP TABLE TEST_BINARY_FLOAT;
DROP TABLE TEST_BINARY_DOUBLE;
DROP TABLE TEST_DOUBLE_PRECISION;
DROP TABLE TEST_CHAR;
DROP TABLE TEST_VARCHAR2;
DROP TABLE TEST_NCHAR;
DROP TABLE TEST_NVARCHAR2;
DROP TABLE TEST_CLOB;
DROP TABLE TEST_NCLOB;
DROP TABLE TEST_BLOB;
DROP TABLE TEST_LONG_RAW;
DROP TABLE TEST_RAW;
DROP TABLE TEST_DATE;
DROP TABLE TEST_TIMESTAMP;
DROP TABLE TEST_TS_TZ;
DROP TABLE TEST_TS_LTZ;
DROP TABLE TEST_INTERVAL_YM;
DROP TABLE TEST_INTERVAL_DS;
DROP TABLE TEST_XMLTYPE;
DROP TABLE TEST_INTEGER;
DROP TABLE TEST_SMALLINT;
COMMIT;
*/